version: '2'
services:
    app:
        build: .
        image: yanfoui-app
        container_name: yafoui-app
        volumes:
           - ./app:/var/app
        environment:
            VIRTUAL_HOST: app-yanfoui.docker
            DOMAIN_NAME: app-yanfoui.docker