version: '2'
services:
    proxy:
        image: jwilder/nginx-proxy
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock:ro"
    app:
        build: .
        image: yanfoui-app
        container_name: yafoui-app
        volumes:
           - ./app:/var/app
        environment:
            VIRTUAL_HOST: app-yanfoui.docker
            DOMAIN_NAME: app-yanfoui.docker